include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_relative_lib_imports: true
    always_put_required_named_parameters_first: false

analyzer:
  enable-experiment:
    - extension-methods

  errors:
    todo: ignore
    invalid_annotation_target: ignore
    constant_identifier_names: ignore

  exclude:
    - .history/**
    - .idea/**
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
    - "test/*"

dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list

  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 4
    source-lines-of-code: 50

  metrics-exclude:
    - .history/**
    - .idea/**
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
    - "test/*"

  rules:
    - avoid-unused-parameters
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-trailing-comma
    - prefer-conditional-expressions
    - no-equal-then-else
